version: '3.8'

services:

  report-api:
    build: .
    container_name: report-api
    environment:
      DB_URL: ${POSTGRES_URL}
      DB_USER: ${POSTGRES_USER}
      DB_PASS: ${POSTGRES_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres:18
    container_name: report-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  rabbitmq:
    image: rabbitmq:4.2-management
    container_name: report-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:8.6.1
    container_name: report-redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
    driver: local